'use client';

/**
 * ComponentRenderer
 *
 * @trace epic: EPIC-07
 * @trace story: STORY-07.11
 * @trace reqs: AC1, AC2, AC3, AC4, AC5, AC7, AC9
 *
 * Why: Completes the end-to-end LLM generation pipeline by rendering JSON configs
 * as actual React components. Validates configs at runtime using STRICT mode,
 * applies security filtering to prevent XSS and prototype pollution, transforms
 * props to match component contracts, and sorts components by order field.
 *
 * This is the critical bridge between Epic-7's LangGraph output and Epic-1/2's
 * React component system. Without this, generated configs cannot be rendered.
 *
 * Security: Uses validateContract with STRICT_VALIDATION_CONFIG to reject
 * invalid configs before rendering. Applies transformProps and filterSafeVariant
 * to block dangerous URLs and prototype pollution attempts.
 *
 * @example
 * ```tsx
 * import ComponentRenderer from '@/components/renderers/ComponentRenderer';
 * import { HomepageConfig } from '@/app/langgraph/agents/schemas';
 *
 * export default function PreviewPage() {
 *   const config: HomepageConfig = loadGeneratedConfig();
 *   return <ComponentRenderer config={config} />;
 * }
 * ```
 */

import { useMemo, useState } from 'react';
import type { ReactElement } from 'react';

// Schema and validation
import { HomepageConfigSchema, type HomepageConfig } from '@/app/langgraph/agents/schemas';
import { validateContract, STRICT_VALIDATION_CONFIG } from '@/lib/contractValidation';

// Security utilities
import { transformProps, filterSafeVariant } from '@/lib/propsTransformation';

// Component imports
// Note: Testimonials and Amenities use named exports
import Navigation from '@/components/blocks/Navigation';
import HeroSection from '@/components/sections/HeroSection';
import RoomsGrid from '@/components/sections/RoomsGrid';
import ImageGallery from '@/components/blocks/ImageGallery';
import { Testimonials } from '@/components/blocks/Testimonials';
import { Amenities } from '@/components/blocks/Amenities';
import BookingWidget from '@/components/blocks/BookingWidget';
import ContactForm from '@/components/sections/ContactForm';
import About from '@/components/sections/About';
import FAQ from '@/components/sections/FAQ';
import Features from '@/components/sections/Features';
import Footer from '@/components/blocks/Footer';

/**
 * Type mapping for all renderable components
 */
type ComponentType =
  | 'navigation'
  | 'hero'
  | 'rooms'
  | 'gallery'
  | 'amenities'
  | 'testimonials'
  | 'booking'
  | 'contact'
  | 'about'
  | 'faq'
  | 'features'
  | 'footer';

/**
 * React component type for component mapping
 */
type ReactComponentType = React.ComponentType<any>;

/**
 * Component type to React component mapping
 *
 * Maps the string type from HomepageConfig to the actual React component.
 */
export const COMPONENT_MAP: Record<ComponentType, ReactComponentType> = {
  navigation: Navigation,
  hero: HeroSection,
  rooms: RoomsGrid,
  gallery: ImageGallery,
  amenities: Amenities,
  testimonials: Testimonials,
  booking: BookingWidget,
  contact: ContactForm,
  about: About,
  faq: FAQ,
  features: Features,
  footer: Footer,
} as const;

/**
 * Export ComponentType for external use
 */
export type { ComponentType };

/**
 * Props for ComponentRenderer
 */
export interface ComponentRendererProps {
  /**
   * The homepage configuration to render
   * Generated by Epic-7's AssemblyAgent and validated at runtime
   */
  config: HomepageConfig;
}

/**
 * Error component for unknown component types
 *
 * Displays a user-friendly error message when an unknown component type
 * is encountered in the config. Renders in development mode with details,
 * shows minimal message in production.
 */
function UnknownComponent({ type }: { type: string }): ReactElement {
  const isDev = process.env.NODE_ENV === 'development';

  return (
    <div className="w-full p-card bg-status-error/faint border border-status-error/subtle rounded-xl">

      <h3 className="text-status-error font-semibold mb-card">
        Unknown Component Type
      </h3>
      <p className="text-status-error-strong">
        The component type <code>&quot;{type}&quot;</code> is not recognized.
      </p>
      {isDev && (
        <p className="text-status-error-strong text-sm mt-2">
          Valid types: {Object.keys(COMPONENT_MAP).join(', ')}
        </p>
      )}
    </div>
  );
}

/**
 * Error boundary for config validation failures
 *
 * Displays error message when HomepageConfigSchema validation fails.
 */
function ConfigErrorBoundary({ error }: { error: Error | null }): ReactElement {
  const isDev = process.env.NODE_ENV === 'development';

  return (
    <div className="w-full min-h-screen flex items-center justify-center p-container">

      <div className="max-w-2xl w-full text-center">
        <div className="text-status-error text-6xl mb-card">!</div>
        <h1 className="text-2xl font-bold text-status-error mb-card">
          Configuration Error
        </h1>
        <p className="text-text-secondary mb-gap-section">
          The generated homepage configuration failed validation.
          This page requires a valid configuration to render.
        </p>
        {isDev && error && (
          <div className="bg-status-error/faint border border-status-error/subtle rounded-xl p-card text-left">

            <p className="text-sm font-semibold text-status-error mb-card">
              Validation Error Details:
            </p>
            <pre className="text-xs text-status-error-strong overflow-auto max-h-64">
              {error.message}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * ComponentRenderer - Main renderer component
 *
 * Accepts a HomepageConfig object and renders all components in order:
 * 1. Validates config using HomepageConfigSchema with STRICT mode (AC9)
 * 2. Sorts components by order field ascending (AC5)
 * 3. For each component:
 *    - Maps type to React component via COMPONENT_MAP (AC2)
 *    - Applies security filtering and prop transformation (AC4)
 *    - Passes sanitized variant to component (AC3)
 *    - Renders component with safe props
 * 4. Handles unknown types with error UI (AC7)
 */
export default function ComponentRenderer({
  config
}: ComponentRendererProps): ReactElement {
  const [error, setError] = useState<Error | null>(null);

  /**
   * SECURITY FIX (AC9): Validate config with STRICT mode before rendering
   * Uses validateContract instead of raw Zod parse to enforce security rules
   */
  const validatedConfig = useMemo(() => {
    try {
      return validateContract(
        HomepageConfigSchema,
        config,
        STRICT_VALIDATION_CONFIG,
        'HomepageConfig'
      );
    } catch (err) {
      const errorObj =
        err instanceof Error ? err : new Error('Invalid config');
      console.error('[ComponentRenderer] Config validation failed:', err);
      setError(errorObj);
      return null;
    }
  }, [config]);

  // Show error UI if validation failed
  if (error || !validatedConfig) {
    return <ConfigErrorBoundary error={error} />;
  }

  /**
   * AC5: Sort components by order field
   * Uses useMemo to prevent unnecessary re-sorts on re-renders
   */
  const sortedComponents = useMemo(
    () =>
      [...validatedConfig.components].sort((a, b) => a.order - b.order),
    [validatedConfig.components]
  );

  return (
    <>
      {sortedComponents.map((componentConfig, index) => {
        const Component = COMPONENT_MAP[componentConfig.type as ComponentType];

        // AC7: Handle unknown component types
        if (!Component) {
          console.error(
            `[ComponentRenderer] Unknown component type: ${componentConfig.type}`
          );
          return (
            <UnknownComponent
              key={`${componentConfig.type}-${index}`}
              type={componentConfig.type}
            />
          );
        }

        // AC4, AC10: Apply security filtering and prop transformation
        // - filterSafeProps: Whitelists allowed keys, blocks dangerous keys
        // - transformProps: Maps field names (heading→title), validates URLs
        const safeProps = transformProps(
          componentConfig.type,
          componentConfig.props
        );

        // AC3: Sanitize variant object to prevent prototype pollution
        const safeVariant = filterSafeVariant(componentConfig.variant);

        return (
          <Component
            key={`${componentConfig.type}-${index}`}
            variant={safeVariant}
            {...safeProps}
          />
        );
      })}
    </>
  );
}
