/**
 * Tests for AnthropicClient.generateWithRetry() - Schema-Guided Reasoning (SGR) Validation Retry
 *
 * Trace:
 *   story: SGR-Phase-1 (Validation Retry Loop)
 *   epic: Infrastructure Improvement
 *   spec: docs/plans/sgr-validation-retry-spec.md
 *
 * Generated by: test-python (test-react pattern)
 *
 * Purpose: Comprehensive unit tests for the generateWithRetry() method that wraps LLM calls
 * with ZOD validation retry loops, feeding errors back to the model for self-correction.
 *
 * Test Cases:
 * 1. Success on first attempt with valid response
 * 2. Retry with ZOD error feedback on validation failure
 * 3. Retry with JSON parse error feedback
 * 4. Throw after max retries exhausted
 * 5. Exponential backoff between retries
 * 6. LangFuse events are logged correctly
 * 7. formatZodError() formats various error types
 * 8. buildRetryPrompt() includes error context
 */

import { AnthropicClient } from '../../app/langgraph/services/AnthropicClient';
import { ComponentSelectorOutputSchema } from '../../app/langgraph/agents/schemas';
import type { ZodError } from 'zod';
import { LangFuseService } from '../../app/langgraph/services/LangFuseService';
import { CostMonitor } from '../../app/langgraph/services/CostMonitor';

// Mock LangFuse to prevent ESM dynamic import errors in Jest
jest.mock('langfuse', () => {
  const mockGeneration = {
    end: jest.fn(),
  };

  const mockTrace = {
    id: 'test-trace-id',
    generation: jest.fn().mockReturnValue(mockGeneration),
    update: jest.fn(),
    score: jest.fn(),
    event: jest.fn(),
  };

  return {
    Langfuse: jest.fn().mockImplementation(() => ({
      trace: jest.fn().mockReturnValue(mockTrace),
      getPrompt: jest.fn().mockRejectedValue(new Error('Mock: Prompt not found')),
      flush: jest.fn().mockResolvedValue(undefined),
      shutdown: jest.fn().mockResolvedValue(undefined),
    })),
  };
});

describe('AnthropicClient.generateWithRetry - SGR Validation Retry', () => {
  let client: AnthropicClient;
  let mockLangfuseService: LangFuseService;
  let mockCostMonitor: CostMonitor;
  let mockTrace: any;
  let mockEvent: jest.Mock;

  beforeEach(() => {
    jest.clearAllMocks();
    mockLangfuseService = new LangFuseService();
    mockCostMonitor = new CostMonitor();

    // Start a trace to get the mock trace object
    mockLangfuseService.startWorkflowTrace('test-generate-with-retry');
    mockTrace = (mockLangfuseService as any).currentTrace;

    // Create a mock event function that returns the trace's event
    mockEvent = jest.fn();
    mockLangfuseService.event = mockEvent;

    client = new AnthropicClient(mockLangfuseService, mockCostMonitor);
  });

  afterEach(async () => {
    await mockLangfuseService.flush();
  });

  const createValidLLMResponse = () => ({
    text: JSON.stringify({
      selectedComponents: ['hero', 'navigation', 'rooms', 'gallery', 'testimonials'],
      layoutStructure: 'single-column' as const,
      emphasisComponents: ['hero'],
      reasoning: 'This is a valid response with sufficient reasoning text to meet the 50 character minimum requirement for the component selector output schema validation.',
    }),
    output: '',
    usage: { input: 100, output: 100, total: 200 },
    model: 'glm-4.7',
    cost: 0.01,
  });

  const createInvalidLLMResponse = (errorType: 'missing' | 'type' | 'enum' | 'length') => {
    const invalidResponses: Record<string, Record<string, unknown>> = {
      missing: {
        // Missing required field: selectedComponents
        layoutStructure: 'single-column',
        emphasisComponents: [],
        reasoning: 'Test reasoning that meets minimum length requirements for the component selector schema validation.',
      },
      type: {
        // Wrong type: selectedComponents should be array
        selectedComponents: 'hero' as unknown as string[],
        layoutStructure: 'single-column' as const,
        emphasisComponents: [],
        reasoning: 'Test reasoning that meets minimum length requirements for the component selector schema validation.',
      },
      enum: {
        // Invalid enum value
        selectedComponents: ['hero', 'navigation', 'rooms', 'gallery', 'testimonials'],
        layoutStructure: 'invalid-layout' as const,
        emphasisComponents: [],
        reasoning: 'Test reasoning that meets minimum length requirements for the component selector schema validation.',
      },
      length: {
        // Array too short (min 5)
        selectedComponents: ['hero', 'rooms'],
        layoutStructure: 'single-column' as const,
        emphasisComponents: [],
        reasoning: 'Test reasoning that meets minimum length requirements for the component selector schema validation.',
      },
    };

    return {
      text: JSON.stringify(invalidResponses[errorType]),
      output: '',
      usage: { input: 100, output: 100, total: 200 },
      model: 'glm-4.7',
      cost: 0.01,
    };
  };

  describe('Test 1: Success on first attempt with valid response', () => {
    it('should return validated response on first successful attempt', async () => {
      // Arrange
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion').mockResolvedValue(validResponse);
      const messages = [{ role: 'user', content: 'Select components for a luxury hotel' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const result = await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert
      expect(result).toEqual({
        selectedComponents: ['hero', 'navigation', 'rooms', 'gallery', 'testimonials'],
        layoutStructure: 'single-column',
        emphasisComponents: ['hero'],
        reasoning: expect.stringContaining('valid response'),
      });
      expect(sendCompletionSpy).toHaveBeenCalledTimes(1);
    });

    it('should not log retry events on first attempt success', async () => {
      // Arrange
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion').mockResolvedValue(validResponse);
      const eventSpy = jest.spyOn(mockLangfuseService as any, 'event');
      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      // No retry events should be logged on first attempt success
      expect(eventSpy).not.toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'validation_retry_attempt',
        })
      );
      expect(sendCompletionSpy).toHaveBeenCalledTimes(1);
    });
  });

  describe('Test 2: Retry with ZOD error feedback on validation failure', () => {
    it('should retry once and succeed with ZOD error feedback', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('missing');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Select components for a luxury hotel' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const result = await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert
      expect(result.selectedComponents).toEqual(['hero', 'navigation', 'rooms', 'gallery', 'testimonials']);
      expect(sendCompletionSpy).toHaveBeenCalledTimes(2);

      // Verify second call includes error feedback in prompt
      const secondCallMessages = sendCompletionSpy.mock.calls[1][0];
      const secondPrompt = secondCallMessages[0].content;
      expect(secondPrompt).toContain('VALIDATION FAILED');
      expect(secondPrompt).toContain('selectedComponents');
      expect(secondPrompt).toMatch(/expected array/);
    });

    it('should log retry attempt event to LangFuse', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('type');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      expect(mockEvent).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'validation_retry_attempt',
        })
      );
      expect(sendCompletionSpy).toHaveBeenCalledTimes(2);
    });

    it('should log retry success event to LangFuse', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('enum');
      const validResponse = createValidLLMResponse();
      jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      expect(mockEvent).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'validation_retry_success',
        })
      );
    });

    it('should handle multiple ZOD validation errors in feedback', async () => {
      // Arrange
      const multipleErrorsResponse = {
        text: JSON.stringify({
          selectedComponents: ['hero', 'rooms'], // Array too short
          layoutStructure: 'invalid' as const, // Invalid enum
          emphasisComponents: ['hero'],
          reasoning: 'short', // Too short (< 50 chars)
        }),
        output: '',
        usage: { input: 100, output: 100, total: 200 },
        model: 'glm-4.7',
        cost: 0.01,
      };

      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(multipleErrorsResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('selectedComponents');
      expect(retryPrompt).toContain('layoutStructure');
      expect(retryPrompt).toContain('reasoning');
    });
  });

  describe('Test 3: Retry with JSON parse error feedback', () => {
    it('should handle malformed JSON with retry feedback', async () => {
      // Arrange - create a response that will fail extractJson (truncated JSON object)
      const malformedJsonResponse = {
        text: '{"selectedComponents": ["hero"', // Truncated - won't parse as valid JSON
        output: '',
        usage: { input: 100, output: 100, total: 200 },
        model: 'glm-4.7',
        cost: 0.01,
      };

      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(malformedJsonResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const result = await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert
      expect(result.selectedComponents).toEqual(['hero', 'navigation', 'rooms', 'gallery', 'testimonials']);
      expect(sendCompletionSpy).toHaveBeenCalledTimes(2);

      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      // When extractJson fails, it throws an error with "Unable to extract JSON"
      expect(retryPrompt).toMatch(/Unable to extract JSON/);
    });

    it('should handle non-JSON text response with retry feedback', async () => {
      // Arrange
      const textOnlyResponse = {
        text: 'I selected these components: hero, navigation, rooms, gallery, testimonials with a single column layout.',
        output: '',
        usage: { input: 100, output: 100, total: 200 },
        model: 'glm-4.7',
        cost: 0.01,
      };

      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(textOnlyResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const result = await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert
      expect(result.selectedComponents).toEqual(['hero', 'navigation', 'rooms', 'gallery', 'testimonials']);
      expect(sendCompletionSpy).toHaveBeenCalledTimes(2);
    });

    it('should handle markdown code block wrapped JSON with retry feedback', async () => {
      // Arrange - extractJson should handle this case
      const markdownWrappedResponse = {
        text: '```json\n{"selectedComponents": ["hero", "rooms"], "layoutStructure": "single-column"}\n```',
        output: '',
        usage: { input: 100, output: 100, total: 200 },
        model: 'glm-4.7',
        cost: 0.01,
      };

      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(markdownWrappedResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const result = await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert
      // First attempt should fail with ZOD error (array too short), then retry and succeed
      expect(result.selectedComponents).toEqual(['hero', 'navigation', 'rooms', 'gallery', 'testimonials']);
      expect(sendCompletionSpy).toHaveBeenCalledTimes(2);
    });
  });

  describe('Test 4: Throw after max retries exhausted', () => {
    it('should throw error after exhausting max retries (default 3)', async () => {
      // Arrange
      const alwaysInvalidResponse = createInvalidLLMResponse('missing');
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValue(alwaysInvalidResponse);

      const mockTrace = (mockLangfuseService as any).currentTrace;
      const logErrorSpy = jest.spyOn(mockLangfuseService, 'logError');

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act & Assert
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options)
      ).rejects.toThrow('failed after 3 attempts');

      expect(sendCompletionSpy).toHaveBeenCalledTimes(3);
      expect(logErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('failed after 3 attempts'),
        expect.any(Object)
      );
    });

    it('should throw error after custom max retries exhausted', async () => {
      // Arrange
      const alwaysInvalidResponse = createInvalidLLMResponse('type');
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValue(alwaysInvalidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act & Assert
      await expect(
        client.generateWithRetry(
          messages,
          ComponentSelectorOutputSchema,
          options,
          2 // Custom max retries
        )
      ).rejects.toThrow('failed after 2 attempts');

      expect(sendCompletionSpy).toHaveBeenCalledTimes(2);
    });

    it('should include formatted ZOD error in final error message', async () => {
      // Arrange
      const alwaysInvalidResponse = createInvalidLLMResponse('enum');
      jest.spyOn(client, 'sendCompletion').mockResolvedValue(alwaysInvalidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act & Assert
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options)
      ).rejects.toThrow('layoutStructure');
    });
  });

  describe('Test 5: Exponential backoff between retries', () => {
    it('should apply exponential backoff: 1s, 2s, 4s', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('length');
      jest.spyOn(client, 'sendCompletion').mockResolvedValue(invalidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const startTime = Date.now();
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options, 3)
      ).rejects.toThrow();
      const duration = Date.now() - startTime;

      // Assert
      // Expected backoff: 1s (first retry) + 2s (second retry) = 3s minimum
      // Plus execution time, so we check for > 2500ms to allow for some variance
      expect(duration).toBeGreaterThan(2500);
    });

    it('should cap backoff at maximum 5000ms', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('missing');
      jest.spyOn(client, 'sendCompletion').mockResolvedValue(invalidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act - with 10 retries, exponential would go 1s, 2s, 4s, 8s... but should cap at 5s
      const startTime = Date.now();
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options, 10)
      ).rejects.toThrow();
      const duration = Date.now() - startTime;

      // Assert
      // With 10 retries and 5s cap, max theoretical time is 9 * 5s = 45s
      // Minimum with caps: 5 retries * 5s cap = 25s minimum
      expect(duration).toBeGreaterThan(20000);
      expect(duration).toBeLessThan(50000); // Should not exceed 50s
    });

    it('should not apply backoff on first attempt success', async () => {
      // Arrange
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion').mockResolvedValue(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const startTime = Date.now();
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);
      const duration = Date.now() - startTime;

      // Assert
      expect(sendCompletionSpy).toHaveBeenCalledTimes(1);
      expect(duration).toBeLessThan(100); // Should be nearly instant
    });
  });

  describe('Test 6: LangFuse events are logged correctly', () => {
    it('should log validation_retry_attempt event with metadata', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('type');
      const validResponse = createValidLLMResponse();
      jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      expect(mockEvent).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'validation_retry_attempt',
        })
      );

      // Verify the event was called with metadata
      const eventCallArgs = mockEvent.mock.calls[0][0];
      expect(eventCallArgs).toHaveProperty('name', 'validation_retry_attempt');
    });

    it('should log validation_retry_success event with attempt number', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('enum');
      const validResponse = createValidLLMResponse();
      jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      expect(mockEvent).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'validation_retry_success',
        })
      );
    });

    it('should log error via logError after max retries', async () => {
      // Arrange
      const alwaysInvalidResponse = createInvalidLLMResponse('length');
      jest.spyOn(client, 'sendCompletion').mockResolvedValue(alwaysInvalidResponse);

      const logErrorSpy = jest.spyOn(mockLangfuseService, 'logError');

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options)
      ).rejects.toThrow();

      // Assert
      expect(logErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('failed after 3 attempts'),
        expect.any(Object)
      );
    });

    it('should include agent name in event metadata', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('missing');
      const validResponse = createValidLLMResponse();
      jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'StylingAgent' as const,
        budgetRemaining: 1.5,
      };

      // Act
      await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert - verify events were logged
      expect(mockEvent).toHaveBeenCalled();
    });
  });

  describe('Test 7: formatZodError() formats various error types', () => {
    it('should format missing required field errors', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('missing');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert - check retry prompt contains formatted error
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('Validation errors:');
      expect(retryPrompt).toMatch(/selectedComponents/);
    });

    it('should format type mismatch errors', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('type');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('Validation errors:');
      expect(retryPrompt).toMatch(/expected array/);
    });

    it('should format enum value errors', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('enum');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toMatch(/Invalid option/);
    });

    it('should format array constraint errors', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('length');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toMatch(/Too small.*>=5 items/);
    });

    it('should format nested path errors correctly', async () => {
      // Arrange - create an error with nested path
      const nestedErrorResponse = {
        text: JSON.stringify({
          selectedComponents: ['hero', 'navigation', 'rooms', 'gallery', 'testimonials'],
          layoutStructure: 'single-column' as const,
          emphasisComponents: ['too', 'many', 'emphasis', 'components', 'here'], // Max 3
          reasoning: 'Test reasoning that meets minimum length requirements for validation.',
        }),
        output: '',
        usage: { input: 100, output: 100, total: 200 },
        model: 'glm-4.7',
        cost: 0.01,
      };

      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(nestedErrorResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('emphasisComponents');
    });
  });

  describe('Test 8: buildRetryPrompt() includes error context', () => {
    it('should include original prompt in retry prompt', async () => {
      // Arrange
      const originalPrompt = 'Select components for a luxury hotel in Paris';
      const invalidResponse = createInvalidLLMResponse('missing');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: originalPrompt }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain(originalPrompt);
    });

    it('should include error message in retry prompt', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('type');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('VALIDATION FAILED');
      expect(retryPrompt).toContain('fix these errors');
    });

    it('should include attempt number in retry prompt', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('enum');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('Attempt 1');
    });

    it('should include retry instructions in prompt', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('length');
      const validResponse = createValidLLMResponse();
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion')
        .mockResolvedValueOnce(invalidResponse)
        .mockResolvedValueOnce(validResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      await client.generateWithRetry(messages, ComponentSelectorOutputSchema, options);

      // Assert
      const retryPrompt = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(retryPrompt).toContain('INSTRUCTIONS FOR RETRY');
      expect(retryPrompt).toContain('Return ONLY a valid JSON object');
      expect(retryPrompt).toContain('ALL required fields');
    });

    it('should preserve attempt number across multiple retries', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('missing');
      jest.spyOn(client, 'sendCompletion').mockResolvedValue(invalidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act - will fail after 3 attempts
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options, 3)
      ).rejects.toThrow();

      // Assert
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion');
      expect(sendCompletionSpy).toHaveBeenCalledTimes(3);

      // Second attempt (first retry)
      const prompt2 = sendCompletionSpy.mock.calls[1][0][0].content;
      expect(prompt2).toContain('Attempt 1');

      // Third attempt (second retry)
      const prompt3 = sendCompletionSpy.mock.calls[2][0][0].content;
      expect(prompt3).toContain('Attempt 2');
    });
  });

  describe('Edge Cases and Additional Coverage', () => {
    it('should handle empty messages array', async () => {
      // Arrange
      const validResponse = createValidLLMResponse();
      jest.spyOn(client, 'sendCompletion').mockResolvedValue(validResponse);

      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act & Assert - should handle gracefully
      const result = await client.generateWithRetry(
        [],
        ComponentSelectorOutputSchema,
        options
      );

      expect(result.selectedComponents).toEqual(['hero', 'navigation', 'rooms', 'gallery', 'testimonials']);
    });

    it('should handle schema with complex nested types', async () => {
      // Arrange - use ComponentSelectorOutputSchema which has complex types
      const complexValidResponse = {
        text: JSON.stringify({
          selectedComponents: ['hero', 'navigation', 'rooms', 'gallery', 'amenities', 'booking', 'contact', 'testimonials'],
          layoutStructure: 'mixed' as const,
          emphasisComponents: ['hero', 'gallery'],
          reasoning: 'A luxury hotel requires comprehensive component coverage with mixed layout to showcase both visual elements and detailed information. The hero section creates immediate impact, while gallery and rooms provide essential details. Mixed layout allows for varied content presentation.',
        }),
        output: '',
        usage: { input: 150, output: 150, total: 300 },
        model: 'glm-4.7',
        cost: 0.02,
      };

      jest.spyOn(client, 'sendCompletion').mockResolvedValue(complexValidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act
      const result = await client.generateWithRetry(
        messages,
        ComponentSelectorOutputSchema,
        options
      );

      // Assert
      expect(result.selectedComponents).toHaveLength(8);
      expect(result.layoutStructure).toBe('mixed');
      expect(result.emphasisComponents).toEqual(['hero', 'gallery']);
    });

    it('should work with zero maxRetries (single attempt only)', async () => {
      // Arrange
      const invalidResponse = createInvalidLLMResponse('missing');
      const sendCompletionSpy = jest.spyOn(client, 'sendCompletion').mockResolvedValue(invalidResponse);

      const messages = [{ role: 'user', content: 'Test prompt' }];
      const options = {
        agentName: 'ComponentSelector' as const,
        budgetRemaining: 2.0,
      };

      // Act & Assert - should fail immediately without retry
      await expect(
        client.generateWithRetry(messages, ComponentSelectorOutputSchema, options, 1)
      ).rejects.toThrow('failed after 1 attempt');

      expect(sendCompletionSpy).toHaveBeenCalledTimes(1);
    });
  });
});
