/**
 * Scale Test Hotel Profiles
 *
 * Story 22.5: Scale Test - Generate 50 Hotels
 *
 * Auto-generated by scripts/generate-hotel-profiles.ts
 * Seed: 12345
 * Generated: 2026-03-16T06:28:52.362Z
 *
 * 50 hotel parameter profiles for scale testing (4-5 per archetype).
 * Profiles include randomized hotel names, global location distribution,
 * and varied audience combinations.
 *
 * @module web-app/fixtures/diversity/scale-test-profiles
 */

import type { HotelParameters } from '@/app/langgraph/agents/schemas';

/**
 * Scale test hotel profiles (50 total)
 *
 * Generated with seed 12345 for reproducibility.
 * Regenerate with: npx tsx scripts/generate-hotel-profiles.ts --seed 12345
 */
export const SCALE_TEST_PROFILES: HotelParameters[] = [
  // 1. Heritage Cultural: Mandarin Oriental Fort Udaipur
  {
    hotelName: 'Mandarin Oriental Fort Udaipur',
    hotelType: 'luxury',
    targetAudience: 'leisure',
    brandPersonality: 'elegant',
    location: 'Barcelona, Spain',
  },
  // 2. Heritage Cultural: Mandarin Oriental Haveli Lucknow
  {
    hotelName: 'Mandarin Oriental Haveli Lucknow',
    hotelType: 'luxury',
    targetAudience: 'business',
    brandPersonality: 'elegant',
    location: 'Berlin, Germany',
  },
  // 3. Heritage Cultural: Taj Culture Kolkata
  {
    hotelName: 'Taj Culture Kolkata',
    hotelType: 'luxury',
    targetAudience: 'leisure',
    brandPersonality: 'elegant',
    location: 'Delhi, India',
  },
  // 4. Heritage Cultural: Imperial Fort Mumbai
  {
    hotelName: 'Imperial Fort Mumbai',
    hotelType: 'luxury',
    targetAudience: 'business',
    brandPersonality: 'elegant',
    location: 'Barcelona, Spain',
  },
  // 5. Heritage Cultural: Mandarin Oriental Haveli New Delhi
  {
    hotelName: 'Mandarin Oriental Haveli New Delhi',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Denarau Island, Fiji',
  },
  // 6. Wellness/Spa: COMO Wellness Sanctuary
  {
    hotelName: 'COMO Wellness Sanctuary',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'friendly',
    location: 'Cancun, Mexico',
  },
  // 7. Wellness/Spa: COMO Wellness Retreat
  {
    hotelName: 'COMO Wellness Retreat',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Cartagena, Colombia',
  },
  // 8. Wellness/Spa: Kamalaya Sanctuary Estate
  {
    hotelName: 'Kamalaya Sanctuary Estate',
    hotelType: 'boutique',
    targetAudience: 'couples',
    brandPersonality: 'friendly',
    location: 'Arusha, Tanzania',
  },
  // 9. Wellness/Spa: Aman Harmony Retreat
  {
    hotelName: 'Aman Harmony Retreat',
    hotelType: 'boutique',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Montevideo, Uruguay',
  },
  // 10. Wellness/Spa: Six Senses Wellness Retreat
  {
    hotelName: 'Six Senses Wellness Retreat',
    hotelType: 'luxury',
    targetAudience: 'leisure',
    brandPersonality: 'elegant',
    location: 'Queenstown, New Zealand',
  },
  // 11. Design/Art Hotel: Standard Museum Cincinnati
  {
    hotelName: 'Standard Museum Cincinnati',
    hotelType: 'boutique',
    targetAudience: 'business',
    brandPersonality: 'adventurous',
    location: 'Santiago, Chile',
  },
  // 12. Design/Art Hotel: Andaz Design Durham
  {
    hotelName: 'Andaz Design Durham',
    hotelType: 'boutique',
    targetAudience: 'couples',
    brandPersonality: 'adventurous',
    location: 'Vienna, Austria',
  },
  // 13. Design/Art Hotel: Andaz Museum Cincinnati
  {
    hotelName: 'Andaz Museum Cincinnati',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Melbourne, Australia',
  },
  // 14. Design/Art Hotel: 21c Gallery Kansas City
  {
    hotelName: '21c Gallery Kansas City',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'adventurous',
    location: 'Cape Town, South Africa',
  },
  // 15. Mountain/Wilderness: Aman Atacama Resort
  {
    hotelName: 'Aman Atacama Resort',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Tokyo, Japan',
  },
  // 16. Mountain/Wilderness: Amangiri Zermatt Adventure
  {
    hotelName: 'Amangiri Zermatt Adventure',
    hotelType: 'resort',
    targetAudience: 'couples',
    brandPersonality: 'adventurous',
    location: 'Florence, Italy',
  },
  // 17. Mountain/Wilderness: Aman Zermatt Wilderness
  {
    hotelName: 'Aman Zermatt Wilderness',
    hotelType: 'resort',
    targetAudience: 'couples',
    brandPersonality: 'adventurous',
    location: 'Toronto, Canada',
  },
  // 18. Mountain/Wilderness: Four Seasons Kruger Expedition
  {
    hotelName: 'Four Seasons Kruger Expedition',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'adventurous',
    location: 'Santiago, Chile',
  },
  // 19. Family Resort: Universal Moorea Island
  {
    hotelName: 'Universal Moorea Island',
    hotelType: 'resort',
    targetAudience: 'family',
    brandPersonality: 'friendly',
    location: 'Denarau Island, Fiji',
  },
  // 20. Family Resort: Disney Punta Cana Island
  {
    hotelName: 'Disney Punta Cana Island',
    hotelType: 'resort',
    targetAudience: 'family',
    brandPersonality: 'friendly',
    location: 'Toronto, Canada',
  },
  // 21. Family Resort: Disney Columbus Isle Village
  {
    hotelName: 'Disney Columbus Isle Village',
    hotelType: 'resort',
    targetAudience: 'family',
    brandPersonality: 'friendly',
    location: 'Rome, Italy',
  },
  // 22. Family Resort: Disney Bora Bora Beach
  {
    hotelName: 'Disney Bora Bora Beach',
    hotelType: 'resort',
    targetAudience: 'family',
    brandPersonality: 'friendly',
    location: 'Athens, Greece',
  },
  // 23. Business Hotel: Hilton Grand Houston
  {
    hotelName: 'Hilton Grand Houston',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'modern',
    location: 'Auckland, New Zealand',
  },
  // 24. Business Hotel: Airport New York
  {
    hotelName: 'Airport New York',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'professional',
    location: 'Singapore, Singapore',
  },
  // 25. Business Hotel: Courtyard Airport San Diego
  {
    hotelName: 'Courtyard Airport San Diego',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'professional',
    location: 'Los Angeles, United States',
  },
  // 26. Business Hotel: Hyatt Grand Phoenix
  {
    hotelName: 'Hyatt Grand Phoenix',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'modern',
    location: 'Seoul, South Korea',
  },
  // 27. Eco Lodge: Green Central Park Lodge
  {
    hotelName: 'Green Central Park Lodge',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Zurich, Switzerland',
  },
  // 28. Eco Lodge: Eco West Hollywood House
  {
    hotelName: 'Eco West Hollywood House',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Bali, Indonesia',
  },
  // 29. Eco Lodge: Miami Inn
  {
    hotelName: 'Miami Inn',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'friendly',
    location: 'Mumbai, India',
  },
  // 30. Eco Lodge: Earth Brooklyn Suites
  {
    hotelName: 'Earth Brooklyn Suites',
    hotelType: 'boutique',
    targetAudience: 'couples',
    brandPersonality: 'friendly',
    location: 'Kyoto, Japan',
  },
  // 31. Boutique Editorial: House Volume Nørrebro
  {
    hotelName: 'House Volume Nørrebro',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Manila, Philippines',
  },
  // 32. Boutique Editorial: Gallery Collection Shoreditch
  {
    hotelName: 'Gallery Collection Shoreditch',
    hotelType: 'boutique',
    targetAudience: 'couples',
    brandPersonality: 'modern',
    location: 'Barcelona, Spain',
  },
  // 33. Boutique Editorial: Studio Editorial Nørrebro
  {
    hotelName: 'Studio Editorial Nørrebro',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Sydney, Australia',
  },
  // 34. Boutique Editorial: The Collection Tribeca
  {
    hotelName: 'The Collection Tribeca',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'adventurous',
    location: 'Petra, Jordan',
  },
  // 35. Quiet Luxury: Retreat Tranquil Boutique
  {
    hotelName: 'Retreat Tranquil Boutique',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Ho Chi Minh City, Vietnam',
  },
  // 36. Quiet Luxury: Villa Tranquil Lodge
  {
    hotelName: 'Villa Tranquil Lodge',
    hotelType: 'luxury',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Sydney, Australia',
  },
  // 37. Quiet Luxury: Haus Haven Boutique
  {
    hotelName: 'Haus Haven Boutique',
    hotelType: 'boutique',
    targetAudience: 'leisure',
    brandPersonality: 'modern',
    location: 'Kyoto, Japan',
  },
  // 38. Quiet Luxury: Retreat Minima Inn
  {
    hotelName: 'Retreat Minima Inn',
    hotelType: 'boutique',
    targetAudience: 'couples',
    brandPersonality: 'modern',
    location: 'London, United Kingdom',
  },
  // 39. Urban Tech-Forward: Neo Node SIN
  {
    hotelName: 'Neo Node SIN',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'modern',
    location: 'London, United Kingdom',
  },
  // 40. Urban Tech-Forward: Neo Matrix Transit
  {
    hotelName: 'Neo Matrix Transit',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'modern',
    location: 'Auckland, New Zealand',
  },
  // 41. Urban Tech-Forward: Neo Link HND
  {
    hotelName: 'Neo Link HND',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'professional',
    location: 'Doha, Qatar',
  },
  // 42. Urban Tech-Forward: Tech Link DXB
  {
    hotelName: 'Tech Link DXB',
    hotelType: 'business',
    targetAudience: 'business',
    brandPersonality: 'modern',
    location: 'San Francisco, United States',
  },
  // 43. Heritage Opulence: The Windsor Palace
  {
    hotelName: 'The Windsor Palace',
    hotelType: 'luxury',
    targetAudience: 'business',
    brandPersonality: 'elegant',
    location: 'Mumbai, India',
  },
  // 44. Heritage Opulence: Imperial Dynasty Estate
  {
    hotelName: 'Imperial Dynasty Estate',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Florence, Italy',
  },
  // 45. Heritage Opulence: Majestic Crown Grand
  {
    hotelName: 'Majestic Crown Grand',
    hotelType: 'luxury',
    targetAudience: 'leisure',
    brandPersonality: 'elegant',
    location: 'Los Angeles, United States',
  },
  // 46. Heritage Opulence: Imperial Sovereign Manor
  {
    hotelName: 'Imperial Sovereign Manor',
    hotelType: 'luxury',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Sydney, Australia',
  },
  // 47. Coastal Resort: Aman Maui Island
  {
    hotelName: 'Aman Maui Island',
    hotelType: 'resort',
    targetAudience: 'couples',
    brandPersonality: 'elegant',
    location: 'Bangkok, Thailand',
  },
  // 48. Coastal Resort: Rosewood Phuket
  {
    hotelName: 'Rosewood Phuket',
    hotelType: 'resort',
    targetAudience: 'family',
    brandPersonality: 'elegant',
    location: 'Buenos Aires, Argentina',
  },
  // 49. Coastal Resort: Four Seasons Le Saint-Geran Retreat
  {
    hotelName: 'Four Seasons Le Saint-Geran Retreat',
    hotelType: 'resort',
    targetAudience: 'family',
    brandPersonality: 'friendly',
    location: 'Lima, Peru',
  },
  // 50. Coastal Resort: Seychelles Villas
  {
    hotelName: 'Seychelles Villas',
    hotelType: 'resort',
    targetAudience: 'couples',
    brandPersonality: 'friendly',
    location: 'Montevideo, Uruguay',
  }
];

/**
 * Get archetype for a scale test profile
 *
 * @param index Profile index (0-49)
 * @returns Archetype name or 'unknown'
 */
export function getScaleTestProfileArchetype(index: number): string {
  const archetypes = [
    'Heritage Cultural',
    'Heritage Cultural',
    'Heritage Cultural',
    'Heritage Cultural',
    'Heritage Cultural',
    'Wellness/Spa',
    'Wellness/Spa',
    'Wellness/Spa',
    'Wellness/Spa',
    'Wellness/Spa',
    'Design/Art Hotel',
    'Design/Art Hotel',
    'Design/Art Hotel',
    'Design/Art Hotel',
    'Mountain/Wilderness',
    'Mountain/Wilderness',
    'Mountain/Wilderness',
    'Mountain/Wilderness',
    'Family Resort',
    'Family Resort',
    'Family Resort',
    'Family Resort',
    'Business Hotel',
    'Business Hotel',
    'Business Hotel',
    'Business Hotel',
    'Eco Lodge',
    'Eco Lodge',
    'Eco Lodge',
    'Eco Lodge',
    'Boutique Editorial',
    'Boutique Editorial',
    'Boutique Editorial',
    'Boutique Editorial',
    'Quiet Luxury',
    'Quiet Luxury',
    'Quiet Luxury',
    'Quiet Luxury',
    'Urban Tech-Forward',
    'Urban Tech-Forward',
    'Urban Tech-Forward',
    'Urban Tech-Forward',
    'Heritage Opulence',
    'Heritage Opulence',
    'Heritage Opulence',
    'Heritage Opulence',
    'Coastal Resort',
    'Coastal Resort',
    'Coastal Resort',
    'Coastal Resort',
  ];
  return archetypes[index] || 'unknown';
}

/**
 * Get all scale test profiles with metadata
 */
export function getScaleTestProfilesWithMetadata(): Array<{
  id: string;
  archetype: string;
  parameters: HotelParameters;
}> {
  return [
    { id: 'scale-test-1', archetype: 'Heritage Cultural', parameters: SCALE_TEST_PROFILES[0] },
    { id: 'scale-test-2', archetype: 'Heritage Cultural', parameters: SCALE_TEST_PROFILES[1] },
    { id: 'scale-test-3', archetype: 'Heritage Cultural', parameters: SCALE_TEST_PROFILES[2] },
    { id: 'scale-test-4', archetype: 'Heritage Cultural', parameters: SCALE_TEST_PROFILES[3] },
    { id: 'scale-test-5', archetype: 'Heritage Cultural', parameters: SCALE_TEST_PROFILES[4] },
    { id: 'scale-test-6', archetype: 'Wellness/Spa', parameters: SCALE_TEST_PROFILES[5] },
    { id: 'scale-test-7', archetype: 'Wellness/Spa', parameters: SCALE_TEST_PROFILES[6] },
    { id: 'scale-test-8', archetype: 'Wellness/Spa', parameters: SCALE_TEST_PROFILES[7] },
    { id: 'scale-test-9', archetype: 'Wellness/Spa', parameters: SCALE_TEST_PROFILES[8] },
    { id: 'scale-test-10', archetype: 'Wellness/Spa', parameters: SCALE_TEST_PROFILES[9] },
    { id: 'scale-test-11', archetype: 'Design/Art Hotel', parameters: SCALE_TEST_PROFILES[10] },
    { id: 'scale-test-12', archetype: 'Design/Art Hotel', parameters: SCALE_TEST_PROFILES[11] },
    { id: 'scale-test-13', archetype: 'Design/Art Hotel', parameters: SCALE_TEST_PROFILES[12] },
    { id: 'scale-test-14', archetype: 'Design/Art Hotel', parameters: SCALE_TEST_PROFILES[13] },
    { id: 'scale-test-15', archetype: 'Mountain/Wilderness', parameters: SCALE_TEST_PROFILES[14] },
    { id: 'scale-test-16', archetype: 'Mountain/Wilderness', parameters: SCALE_TEST_PROFILES[15] },
    { id: 'scale-test-17', archetype: 'Mountain/Wilderness', parameters: SCALE_TEST_PROFILES[16] },
    { id: 'scale-test-18', archetype: 'Mountain/Wilderness', parameters: SCALE_TEST_PROFILES[17] },
    { id: 'scale-test-19', archetype: 'Family Resort', parameters: SCALE_TEST_PROFILES[18] },
    { id: 'scale-test-20', archetype: 'Family Resort', parameters: SCALE_TEST_PROFILES[19] },
    { id: 'scale-test-21', archetype: 'Family Resort', parameters: SCALE_TEST_PROFILES[20] },
    { id: 'scale-test-22', archetype: 'Family Resort', parameters: SCALE_TEST_PROFILES[21] },
    { id: 'scale-test-23', archetype: 'Business Hotel', parameters: SCALE_TEST_PROFILES[22] },
    { id: 'scale-test-24', archetype: 'Business Hotel', parameters: SCALE_TEST_PROFILES[23] },
    { id: 'scale-test-25', archetype: 'Business Hotel', parameters: SCALE_TEST_PROFILES[24] },
    { id: 'scale-test-26', archetype: 'Business Hotel', parameters: SCALE_TEST_PROFILES[25] },
    { id: 'scale-test-27', archetype: 'Eco Lodge', parameters: SCALE_TEST_PROFILES[26] },
    { id: 'scale-test-28', archetype: 'Eco Lodge', parameters: SCALE_TEST_PROFILES[27] },
    { id: 'scale-test-29', archetype: 'Eco Lodge', parameters: SCALE_TEST_PROFILES[28] },
    { id: 'scale-test-30', archetype: 'Eco Lodge', parameters: SCALE_TEST_PROFILES[29] },
    { id: 'scale-test-31', archetype: 'Boutique Editorial', parameters: SCALE_TEST_PROFILES[30] },
    { id: 'scale-test-32', archetype: 'Boutique Editorial', parameters: SCALE_TEST_PROFILES[31] },
    { id: 'scale-test-33', archetype: 'Boutique Editorial', parameters: SCALE_TEST_PROFILES[32] },
    { id: 'scale-test-34', archetype: 'Boutique Editorial', parameters: SCALE_TEST_PROFILES[33] },
    { id: 'scale-test-35', archetype: 'Quiet Luxury', parameters: SCALE_TEST_PROFILES[34] },
    { id: 'scale-test-36', archetype: 'Quiet Luxury', parameters: SCALE_TEST_PROFILES[35] },
    { id: 'scale-test-37', archetype: 'Quiet Luxury', parameters: SCALE_TEST_PROFILES[36] },
    { id: 'scale-test-38', archetype: 'Quiet Luxury', parameters: SCALE_TEST_PROFILES[37] },
    { id: 'scale-test-39', archetype: 'Urban Tech-Forward', parameters: SCALE_TEST_PROFILES[38] },
    { id: 'scale-test-40', archetype: 'Urban Tech-Forward', parameters: SCALE_TEST_PROFILES[39] },
    { id: 'scale-test-41', archetype: 'Urban Tech-Forward', parameters: SCALE_TEST_PROFILES[40] },
    { id: 'scale-test-42', archetype: 'Urban Tech-Forward', parameters: SCALE_TEST_PROFILES[41] },
    { id: 'scale-test-43', archetype: 'Heritage Opulence', parameters: SCALE_TEST_PROFILES[42] },
    { id: 'scale-test-44', archetype: 'Heritage Opulence', parameters: SCALE_TEST_PROFILES[43] },
    { id: 'scale-test-45', archetype: 'Heritage Opulence', parameters: SCALE_TEST_PROFILES[44] },
    { id: 'scale-test-46', archetype: 'Heritage Opulence', parameters: SCALE_TEST_PROFILES[45] },
    { id: 'scale-test-47', archetype: 'Coastal Resort', parameters: SCALE_TEST_PROFILES[46] },
    { id: 'scale-test-48', archetype: 'Coastal Resort', parameters: SCALE_TEST_PROFILES[47] },
    { id: 'scale-test-49', archetype: 'Coastal Resort', parameters: SCALE_TEST_PROFILES[48] },
    { id: 'scale-test-50', archetype: 'Coastal Resort', parameters: SCALE_TEST_PROFILES[49] }
  ];
}
